[package]
name = "rcat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
rand = "0.9.0"
tokio = { version = "1.43.0", features = ["full"] }
tokio-rustls = "0.26.1"
webpki-roots = "0.26.8"
